[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.40.0", features = ["lazy", "csv"] }
rand = "0.8"
windows = { version = "0.56.0", features = [
    "Win32_System_ProcessStatus",
    "Win32_System_Threading"
] }
